// Code generated by MockGen. DO NOT EDIT.
// Source: product/repository/product.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	reflect "reflect"
	model "wire-clean-architecture/product/model"

	gomock "github.com/golang/mock/gomock"
)

// MockIProductRepository is a mock of IProductRepository interface.
type MockIProductRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIProductRepositoryMockRecorder
}

// MockIProductRepositoryMockRecorder is the mock recorder for MockIProductRepository.
type MockIProductRepositoryMockRecorder struct {
	mock *MockIProductRepository
}

// NewMockIProductRepository creates a new mock instance.
func NewMockIProductRepository(ctrl *gomock.Controller) *MockIProductRepository {
	mock := &MockIProductRepository{ctrl: ctrl}
	mock.recorder = &MockIProductRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIProductRepository) EXPECT() *MockIProductRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockIProductRepository) Delete(product model.Product) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Delete", product)
}

// Delete indicates an expected call of Delete.
func (mr *MockIProductRepositoryMockRecorder) Delete(product interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIProductRepository)(nil).Delete), product)
}

// FindAll mocks base method.
func (m *MockIProductRepository) FindAll() []model.Product {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].([]model.Product)
	return ret0
}

// FindAll indicates an expected call of FindAll.
func (mr *MockIProductRepositoryMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockIProductRepository)(nil).FindAll))
}

// FindByID mocks base method.
func (m *MockIProductRepository) FindByID(id uint) model.Product {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(model.Product)
	return ret0
}

// FindByID indicates an expected call of FindByID.
func (mr *MockIProductRepositoryMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockIProductRepository)(nil).FindByID), id)
}

// Save mocks base method.
func (m *MockIProductRepository) Save(product model.Product) model.Product {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", product)
	ret0, _ := ret[0].(model.Product)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockIProductRepositoryMockRecorder) Save(product interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockIProductRepository)(nil).Save), product)
}
