// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/jinzhu/gorm"
	"wire-clean-architecture/product/controller"
	"wire-clean-architecture/product/repository"
	"wire-clean-architecture/product/usecase"
)

import (
	_ "github.com/jinzhu/gorm/dialects/mysql"
)

// Injectors from wire.go:

func InitProductController(db *gorm.DB) controller.ProductController {
	iProductRepository := repository.ProvideProductRepostiory(db)
	getAllProductsUsecase := usecase.ProvideGetAllProductsUsecase(iProductRepository)
	getProductUsecase := usecase.ProvideGetProductUsecase(iProductRepository)
	deleteProductUsecase := usecase.ProvideDeleteProductUsecase(iProductRepository, getProductUsecase)
	updateProductUsecase := usecase.ProvideUpdateProductUsecase(iProductRepository, getProductUsecase)
	createProductUsecase := usecase.ProvideCreateProductUsecase(iProductRepository, getProductUsecase)
	productController := controller.ProvideProductController(getAllProductsUsecase, getProductUsecase, deleteProductUsecase, updateProductUsecase, createProductUsecase)
	return productController
}
